### PR TITLE
ARM templates for GCC hybrid deployment

### PR DESCRIPTION
**Pull request by v-smahaj**
Added ARM templates for GCC hybrid deployments.
In hybrid setup, the Office 365 users and Microsoft Teams services are hosted in a different Azure AD tenant as the Azure resources. Also, both O365 and Azure use a Government Cloud:
- Office 365 with a GCC Azure AD tenant. Creating Bot channel registration in this tenant. 
- Azure Government (https://portal.azure.us) associated to its GCC-H Azure AD tenant. Creating remaining resources in this tenant.

### CODE REVIEW

**Comment by aosolis** [comment]
@v-smahaj can you follow the same pattern as in the other GCC enablement PRs, where we out the new templates in a GCC folder?

**Review by aosolis — CHANGES_REQUESTED** [review]
Please follow same pattern as in other GCC enablement PRs.

**Comment by v-smahaj** [comment]
> @v-smahaj can you follow the same pattern as in the other GCC enablement PRs, where we out the new templates in a GCC folder?

Added GCC ARM templates to GCC folder.

**Comment by v-smahaj** [comment]
> Please follow same pattern as in other GCC enablement PRs.

Done. Added ARM templates to GCC folder.

**Review by aosolis — APPROVED** [review]

**Pull request merged**
